Solve undefined reference to 'setdisk' This function is for changing the drive letter, so it can be simply avoided in Linux. Sigala took the same approach.